(() => {
  "use strict";
  const API="/api/v1/gallery";
  const e={grid:document.querySelector("#gallery-grid"),search:document.querySelector("#gallery-search"),category:document.querySelector("#gallery-category"),reset:document.querySelector("#gallery-reset"),resultCount:document.querySelector("#gallery-result-count"),status:document.querySelector("#gallery-status"),loading:document.querySelector("#gallery-loading"),empty:document.querySelector("#gallery-empty"),noResults:document.querySelector("#gallery-no-results"),noResultsReset:document.querySelector("#gallery-no-results-reset"),error:document.querySelector("#gallery-error"),retry:document.querySelector("#gallery-retry"),pagination:document.querySelector("#gallery-pagination"),lightbox:document.querySelector("#gallery-lightbox"),lightboxDialog:document.querySelector(".lightbox-dialog"),lightboxImage:document.querySelector("#lightbox-image"),lightboxLoading:document.querySelector("#lightbox-loading"),lightboxFallback:document.querySelector("#lightbox-fallback"),lightboxClose:document.querySelector("#lightbox-close"),lightboxPrev:document.querySelector("#lightbox-prev"),lightboxNext:document.querySelector("#lightbox-next"),lightboxTitle:document.querySelector("#lightbox-title"),lightboxDescription:document.querySelector("#lightbox-description"),lightboxMeta:document.querySelector("#lightbox-meta")};
  const s={items:[],filtered:[],page:1,pageSize:12,index:-1,lastFocus:null};
  function setLoading(v){e.loading.hidden=!v;e.grid.hidden=v;if(v){e.empty.hidden=true;e.noResults.hidden=true;e.error.hidden=true;e.pagination.hidden=true;e.status.textContent="Loading available gallery images.";}}
  function setError(msg){e.loading.hidden=true;e.grid.hidden=true;e.empty.hidden=true;e.noResults.hidden=true;e.pagination.hidden=true;e.error.hidden=false;e.resultCount.textContent="Gallery unavailable";e.status.textContent=msg;}
  function request(){return fetch(API,{credentials:"include",headers:{Accept:"application/json"}}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Unable to load gallery.");return Array.isArray(d.data)?d.data:[];});}
  function normalize(item){return {id:String(item.id),title:String(item.title||"Gallery image"),description:String(item.description||""),imageUrl:String(item.imageUrl||""),thumbnailUrl:String(item.thumbnailUrl||item.imageUrl||""),category:String(item.category||""),collection:String(item.collection||""),publishedDate:String(item.publishedAt||item.uploadedAt||""),altText:String(item.altText||item.title||"Gallery image")};}
  function filtered(){const q=e.search.value.trim().toLowerCase(),cat=e.category.value;return s.items.filter(x=>(!q||[x.title,x.description,x.category,x.collection].join(" ").toLowerCase().includes(q))&&(!cat||x.category===cat));}
  function populate(){const cats=[...new Set(s.items.map(x=>x.category).filter(Boolean))].sort();const current=e.category.value;e.category.replaceChildren(new Option("All categories",""));cats.forEach(c=>e.category.add(new Option(c,c)));e.category.disabled=!cats.length;if(cats.includes(current))e.category.value=current;else e.category.value="";}
  function render(){if(!e.grid)return;s.filtered=filtered();const total=s.filtered.length,pages=Math.max(1,Math.ceil(total/s.pageSize));if(s.page>pages)s.page=pages;const start=(s.page-1)*s.pageSize;e.grid.replaceChildren();e.empty.hidden=s.items.length!==0;e.noResults.hidden=!(s.items.length&&total===0);e.grid.hidden=!s.items.length||!total;e.pagination.hidden=total<=s.pageSize;e.resultCount.textContent=`${total} image${total===1?"":"s"}`;e.status.textContent=!s.items.length?"No gallery images are currently available to members.":total?"Gallery images available.":"No gallery images match the current search or filter.";s.filtered.slice(start,start+s.pageSize).forEach((item,i)=>e.grid.appendChild(card(item,start+i)));renderPages(pages);e.reset.hidden=!(e.search.value||e.category.value);}
  function card(item,index){const a=document.createElement("article");a.className="gallery-card";const b=document.createElement("button");b.type="button";b.className="gallery-card-button";b.setAttribute("aria-label",`Open ${item.title} image`);const wrap=document.createElement("div");wrap.className="gallery-image-wrap";const img=document.createElement("img");img.className="gallery-image";img.src=item.thumbnailUrl;img.alt=item.altText;img.loading="lazy";img.decoding="async";const fallback=document.createElement("div");fallback.className="gallery-image-fallback";fallback.hidden=true;fallback.textContent="Image unavailable";img.addEventListener("error",()=>{img.hidden=true;fallback.hidden=false},{once:true});wrap.append(img,fallback);const body=document.createElement("div");body.className="gallery-card-body";const h=document.createElement("div");h.className="gallery-card-heading";const title=document.createElement("h3");title.className="gallery-card-title";title.textContent=item.title;h.appendChild(title);if(item.category){const tag=document.createElement("span");tag.className="tag";tag.textContent=item.category;h.appendChild(tag);}body.appendChild(h);if(item.description){const p=document.createElement("p");p.className="gallery-card-description";p.textContent=item.description;body.appendChild(p);}b.append(wrap,body);a.appendChild(b);b.addEventListener("click",()=>open(index));return a;}
  function renderPages(pages){e.pagination.replaceChildren();if(pages<=1){e.pagination.hidden=true;return;}const btn=(label,page,disabled,current)=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.disabled=disabled;if(current)b.setAttribute("aria-current","page");b.addEventListener("click",()=>{s.page=page;render();});return b;};e.pagination.append(btn("Previous",s.page-1,s.page===1,false));for(let i=1;i<=pages;i++)e.pagination.append(btn(String(i),i,false,i===s.page));e.pagination.append(btn("Next",s.page+1,s.page===pages,false));}
  function open(i){if(!s.filtered[i])return;s.index=i;s.lastFocus=document.activeElement;const item=s.filtered[i];e.lightbox.hidden=false;e.lightboxImage.hidden=false;e.lightboxFallback.hidden=true;e.lightboxLoading.hidden=false;e.lightboxImage.src=item.imageUrl;e.lightboxImage.alt=item.altText;e.lightboxTitle.textContent=item.title;e.lightboxDescription.textContent=item.description||"No description available.";e.lightboxMeta.textContent=item.category||"";e.lightboxPrev.disabled=i<=0;e.lightboxNext.disabled=i>=s.filtered.length-1;document.body.classList.add("modal-open");e.lightboxClose.focus();}
  function close(){e.lightbox.hidden=true;document.body.classList.remove("modal-open");s.lastFocus?.focus?.();}
  function reset(){e.search.value="";e.category.value="";s.page=1;render();e.search.focus();}
  e.search?.addEventListener("input",()=>{s.page=1;render();});e.category?.addEventListener("change",()=>{s.page=1;render();});e.reset?.addEventListener("click",reset);e.noResultsReset?.addEventListener("click",reset);e.retry?.addEventListener("click",load);e.lightboxClose?.addEventListener("click",close);e.lightboxPrev?.addEventListener("click",()=>open(s.index-1));e.lightboxNext?.addEventListener("click",()=>open(s.index+1));document.addEventListener("keydown",ev=>{if(e.lightbox.hidden)return;if(ev.key==="Escape")close();if(ev.key==="ArrowLeft"&&s.index>0)open(s.index-1);if(ev.key==="ArrowRight"&&s.index<s.filtered.length-1)open(s.index+1);});
  function load(){setLoading(true);request().then(data=>{s.items=data.map(normalize).filter(x=>x.imageUrl);populate();s.page=1;render();setLoading(false);e.grid.hidden=!s.items.length;}).catch(err=>setError(err.message||"Unable to load gallery."));}
  load();
})();