const holidayRepository=require("../repositories/holidayRepository");
const TYPES=new Set(["Public Holiday","Company Holiday","Optional Holiday","Other"]);
const STATUSES=new Set(["Active","Inactive"]);
function err(message,statusCode=400,errors=null){const e=new Error(message);e.statusCode=statusCode;if(errors)e.errors=errors;return e}
function id(v){const n=Number(v);if(!Number.isInteger(n)||n<=0)throw err("Invalid holiday ID.");return n}
function date(v){if(typeof v!=="string"||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(v)||Number.isNaN(new Date(v+"T00:00:00Z").getTime())||new Date(v+"T00:00:00Z").toISOString().slice(0,10)!==v)throw err("Invalid holiday date.",400,{date:"Use a valid YYYY-MM-DD date."});return v}
function validate(input,partial=false){const errors={},out={};if(!partial||input.name!==undefined){const n=String(input.name||"").trim();if(!n||n.length>120)errors.name="Holiday name is required and must be 120 characters or fewer.";else out.name=n}if(!partial||input.date!==undefined){try{out.date=date(input.date)}catch(e){Object.assign(errors,e.errors||{date:e.message})}}if(!partial||input.description!==undefined){const d=String(input.description||"").trim();if(d.length>500)errors.description="Description must not exceed 500 characters.";else out.description=d}if(!partial||input.type!==undefined){const t=String(input.type||"");if(!TYPES.has(t))errors.type="Invalid holiday type.";else out.type=t}if(input.recurring!==undefined)out.recurring=Boolean(input.recurring);if(input.status!==undefined){const s=String(input.status||"");if(!STATUSES.has(s))errors.status="Invalid holiday status.";else out.status=s}if(Object.keys(errors).length)throw err("Please correct the holiday information.",400,errors);return out}
async function listHolidays(query={}){const year=query.year?Number(query.year):null;if(year!==null&&(!Number.isInteger(year)||year<2000||year>2100))throw err("Invalid year.");return holidayRepository.list({year,type:query.type, status:query.status, search:query.search})}
async function get(idValue){const h=await holidayRepository.findById(id(idValue));if(!h)throw err("Holiday not found.",404);return h}
async function create(userId,input){const data=validate(input);data.createdBy=userId;const duplicate=await holidayRepository.list({year:Number(data.date.slice(0,4)),search:data.name});if(duplicate.some(h=>h.date===data.date&&h.name.toLowerCase()===data.name.toLowerCase()))throw err("A holiday with the same name and date already exists.",409);return holidayRepository.create(data)}
async function update(idValue,input){const holiday=await get(idValue),data=validate(input,true);const merged={name:holiday.name,date:holiday.date,description:holiday.description,type:holiday.type,recurring:Boolean(holiday.recurring),status:holiday.status,...data};const duplicate=await holidayRepository.list({year:Number(merged.date.slice(0,4)),search:merged.name});if(duplicate.some(h=>h.id!==holiday.id&&h.date===merged.date&&h.name.toLowerCase()===merged.name.toLowerCase()))throw err("A holiday with the same name and date already exists.",409);return holidayRepository.update(holiday.id,merged)}
async function remove(idValue){const holiday=await get(idValue);await holidayRepository.remove(holiday.id);return holiday}
module.exports={listHolidays,get,create,update,remove};